openapi: 3.0.3
info:
  title: Pet Paradise Store API
  version: '1.0.0'
  description: A comprehensive pet store management system for managing pets, animals, and pet supplies
paths:
  /pets:
    get:
      operationId: getAllPets
      summary: Retrieve all available pets
      description: Get a list of all pets available in the store
  /pets/{petId}:
    get:
      operationId: getPetById
      summary: Get pet details by ID
  /animals:
    get:
      operationId: listAnimals
      summary: List all animals in inventory
  /inventory:
    get:
      operationId: getInventory
      summary: Get pet store inventory
