openapi: 3.0.3
info:
  title: Pet Store API
  description: A sample API for managing pets in a pet store. Supports CRUD operations for pets, orders, and users.
  version: 1.0.0
  contact:
    name: API Support
    email: support@petstore.com
servers:
  - url: https://api.petstore.com/v1
paths:
  /pets:
    get:
      summary: List all pets
      description: Returns a list of all pets in the store
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          schema:
            type: integer
            default: 20
        - name: status
          in: query
          description: Filter by pet status
          schema:
            type: string
            enum: [available, pending, sold]
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Create a new pet
      description: Add a new pet to the store
      operationId: createPet
      tags:
        - pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
  /pets/{petId}:
    get:
      summary: Get a pet by ID
      description: Returns a single pet by its ID
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A pet object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
    put:
      summary: Update a pet
      description: Update an existing pet in the store
      operationId: updatePet
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet updated successfully
    delete:
      summary: Delete a pet
      description: Remove a pet from the store
      operationId: deletePet
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Pet deleted successfully
  /orders:
    get:
      summary: List all orders
      description: Returns a list of all pet orders
      operationId: listOrders
      tags:
        - orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Place an order
      description: Place a new order for a pet
      operationId: createOrder
      tags:
        - orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order placed successfully
components:
  schemas:
    Pet:
      type: object
      required:
        - name
        - species
      properties:
        id:
          type: string
          description: Unique identifier for the pet
        name:
          type: string
          description: Name of the pet
        species:
          type: string
          description: Species of the pet (dog, cat, bird, etc.)
        breed:
          type: string
          description: Breed of the pet
        age:
          type: integer
          description: Age of the pet in years
        status:
          type: string
          enum: [available, pending, sold]
          description: Current status of the pet
        price:
          type: number
          format: float
          description: Price of the pet
    Order:
      type: object
      required:
        - petId
        - quantity
      properties:
        id:
          type: string
          description: Unique identifier for the order
        petId:
          type: string
          description: ID of the pet being ordered
        quantity:
          type: integer
          description: Number of pets ordered
        shipDate:
          type: string
          format: date-time
          description: Estimated shipping date
        status:
          type: string
          enum: [placed, approved, delivered]
          description: Current status of the order
